toolkit:
  split: magneton/toolkit/configs/config_split.yaml
  merge: magneton/toolkit/configs/config_merge.yaml
  prec: magneton/toolkit/configs/config_prec.yaml
  downsample: magneton/toolkit/configs/config_downsample.yaml
  gen_mask: magneton/toolkit/configs/config_gen_mask.yaml
  mask_prec: magneton/toolkit/configs/config_mask.yaml
  mask_tif: magneton/toolkit/configs/config_mask_tif.yaml
  resize_tif: magneton/toolkit/configs/config_resize_tif.yaml
  
affinity_prediction:
  config_base: magneton/pytorch_connectomics/configs/SNEMI/SNEMI-Base.yaml
  config_file: magneton/pytorch_connectomics/configs/SNEMI/SNEMI-Affinity-UNet.yaml
  checkpoint: /gpfs/marilyn/pi/kuan/shared/FIB_SEM/WORM/pretrain_checkpoint/checkpoint_110000.pth.tar
  hpc: magneton/pytorch_connectomics/configs/hpc.yaml
  
instance_segmentation:
  main: magneton/instance_segmentation/configs/config.yaml
  
